### ISSUE TITLE
Social feed tweaks

### ISSUE THREAD

**Issue by willbunnett** [jakewelchert/legit-action-full-stie#10]
From our QA:
-Facebook is displaying huge photos. Also, on the Twitter feed it says "Follow Button" which seems like it shouldn't be there. 
![social feed](https://cloud.githubusercontent.com/assets/22330611/26017405/33a164f6-371e-11e7-979a-c58e4da6c727.png)

**Comment by jakewelchert** [comment]
Resolved.
