### ISSUE TITLE
Menu is displaying odd

### ISSUE THREAD

**Issue by marleepiette** [jakewelchert/legit-action-full-stie#12]
When we add pages to the site, the menu moves behind the logo so some of the links disappear.

**Comment by willbunnett** [comment]
@jakewelchert Just making sure you see this

**Comment by jakewelchert** [comment]
Yep, seeing these come through. Sorry I'm slow to email as I'm still in California and offline. This issue should be resolved. 

When adding a page, make sure there's at least a header image in place as the navigation height is depicted by this. Will there be instances where there's not a header image? If so should I make it so there's a minimum height so it's independent of the header image?

**Comment by willbunnett** [comment]
Not anticipating any instances where we'd skip the header image, but if it's pretty easy to add a minimum height there, we might as well.

**Comment by jakewelchert** [comment]
Resolved.
