### ISSUE TITLE
Stock images

### ISSUE THREAD

**Issue by marleepiette** [jakewelchert/legit-action-full-stie#13]
This is not an issue per se but could you purchase the stock images on the site and we will reimburse you? If that doesn't work, let us know how you would like us to go about it. Thanks!

**Comment by willbunnett** [comment]
@jakewelchert Just making sure you see this

**Comment by jakewelchert** [comment]
Yep, seeing these come through. Sorry I'm slow to email as I'm still in California and offline.

I can look into purchasing these when I'm back in the office. Is there a certain licensing option you'd like? Royalty free, or will they ever be used for print?

**Comment by willbunnett** [comment]
They will not be used in print

**Comment by jakewelchert** [comment]
These have been purchased, re-sized, and uploaded to the site. I'll also send the full version of the images to you once we're finished with the site. Resolved.
