### ISSUE TITLE
Headline on HTML video not showing up

### ISSUE THREAD

**Issue by marleepiette** [jakewelchert/legit-action-full-stie#14]
Although I see it in the Wordpress form the headline on the HTML video on the front page does not show up to me when I view the whole site.

**Comment by marleepiette** [comment]
Additionally, there should be a play button with a lightbox for a YouTube video on the same video. I don't see that either.

**Comment by willbunnett** [comment]
@jakewelchert Just making sure you see this

**Comment by jakewelchert** [comment]
Yep, seeing these come through. Sorry I'm slow to email as I'm still in California and offline.

@marleepiette Are you not seeing the headline on desktop sizes, or mobile/tablet? Also, what sizes are you not seeing the pop-up?

**Comment by marleepiette** [comment]
Looks like I'm seeing it correctly now on all sizes...I'm not sure why but good news!

**Comment by jakewelchert** [comment]
Resolved.
