### ISSUE TITLE
Main nav: functionality request

### ISSUE THREAD

**Issue by willbunnett** [jakewelchert/legit-action-full-stie#15]
Hey Jake, we can forget this if it takes a lot of work on your end, but would it be possible to have the sub menus expand when someone clicks on the main nav item on desktop? 

So, for the current nav, the About section is the only one that has sub items. But it's also its own page. When people go to that page, I'd like for them to be able to see the sub items. Otherwise, without the sub items expanding on hover, I'm slightly worried people may not realize the sub-nav is a thing.

**Comment by jakewelchert** [comment]
@willbunnett Would this be better if they expanded on hover? Or, would it be better to put the main page in the sub-list? So, About would have About as an option?

**Comment by willbunnett** [comment]
@jakewelchert I guess I'd prefer the second option, if they're both equally easy.

**Comment by willbunnett** [comment]
^^ Assuming that clicking on the top-level "About" would just bring the list down and not go directly to the About page.

**Comment by jakewelchert** [comment]
Resolved. Resorted back to your original thought of having the navigation expanded when you land on the page. So, now when you go to About, the menu is open to show the additional pages.
