### ISSUE TITLE
Question on adding a heading to the social post feature

### ISSUE THREAD

**Issue by marleepiette** [jakewelchert/legit-action-full-stie#16]
Hi Jake,

Would be possible to add a "Follow us on Twitter" header above the Twitter feed and a "Follow us on Facebook" above the Facebook feed. Is this a big deal to add in at this point? If it's possible, we'd like to add it, but it's not the end of the world.

Thanks!

**Comment by jakewelchert** [comment]
These are now added to the site. Resolved.
