### ISSUE TITLE
Question/

### ISSUE THREAD

**Issue by marleepiette** [jakewelchert/legit-action-full-stie#17]

**Comment by marleepiette** [comment]
Whoops, submitted too quickly.

Is it possible to add a separate disclaimer on the PAC page on the website that would say "Paid for by LegitPAC" instead of LegitAction?

Also - before you start that, could you give us an update on how much you're going to be billing us for so far? Thanks!

**Comment by jakewelchert** [comment]
@marleepiette Yes, this is doable. I will need to duplicate the footer for that particular page and make the edit. Shouldn't take more than 30mins.

As far as billing goes, I'm still 6 hours under the original estimate for the project. I imagine with any remaining items and getting it launched I'll be just under the proposal amount. So we're good!

**Comment by jakewelchert** [comment]
This is updated. You can now edit the legal language via a form on each page in WordPress. It will default to 'Paid for by LEGITACTION, INC.' so there's no need to enter anything when creating a new page.

**Comment by marleepiette** [comment]
So apparently, a disclaimer that something was paid for by a PAC has to be centered an in a box. Is it possible to make that change now?
