### ISSUE TITLE
Landing page: Question: Image slot

### ISSUE THREAD

**Issue by willbunnett** [jakewelchert/legit-action-full-stie#3]
One concern I have with this landing page design is that the image banner may push the form too low. For that reason, I want to make sure that we have the ability to select no image for that slot -- and that if we do, the vertical space taken up by the photo collapses. If that makes any sense. 

Can you confirm that that is the way this page will function?

**Comment by jakewelchert** [comment]
@willbunnett Your comments make sense and it should be fine. Would it be better to have the signup form above the text?

**Comment by willbunnett** [comment]
On mobile it would make sense, yah. Is that what you meant?

**Comment by jakewelchert** [comment]
Sounds good, I'll edit.

**Comment by jakewelchert** [comment]
@willbunnett This has been resolved on all pages. On mobile, the sign up and contribute modules push to the top. On tablet they're split, and then desktop they go to their designated spots.

Are you feeling better about this? Is there anything you think we could improve on?

**Comment by willbunnett** [comment]
@jakewelchert Looks like the mobile version of the landing page now has two signup forms, one at the very top and one at the bottom. Should just have one form.

**Comment by jakewelchert** [comment]
@willbunnett Can you try refreshing this page on your end to see if that gets rid of it? Most likely a small cache issue.

**Comment by willbunnett** [comment]
Definitely still there when I refresh

**Comment by jakewelchert** [comment]
@willbunnett Can you check this one more time on the WordPress link: http://legitaction.apps-1and1.com/landing-page

**Comment by willbunnett** [comment]
@jakewelchert Now the second signup form is gone on mobile and desktop

**Comment by jakewelchert** [comment]
Resolved.
