### ISSUE TITLE
Homepage: Bug: CTA button is off center on mobile

### ISSUE THREAD

**Issue by willbunnett** [jakewelchert/legit-action-full-stie#5]
![screenshot may 2 2017 1-52-38 pm](https://cloud.githubusercontent.com/assets/22330611/25639103/846f537a-2f3f-11e7-9481-387f9275b47f.png)

Chrome for Android

**Comment by jakewelchert** [comment]
This was a font size issue. Resolved.

**Comment by willbunnett** [comment]
Still looks unresolved on my device.
