### ISSUE TITLE
Homepage and Interior pages: Bug: Customizable contribute button validation errors

### ISSUE THREAD

**Issue by willbunnett** [jakewelchert/legit-action-full-stie#6]
The customizable amount contribute area on the home and interior pages isn't directing to ActBlue. Instead, it puts up an error page that says email and zip are required. Notably, when email and zip are filled out above, it still doesn't work.

**Comment by jakewelchert** [comment]
Will address this as we move into the CMS. Thanks for noting.

**Comment by jakewelchert** [comment]
Resolved.
