### ISSUE TITLE
SOCIAL LINKS?

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/legit-action-full-stie#8]
@willbunnett Noticing that there are no social media icons/links on the full site. Is that something that needs to be added. Previously they were in the footer.

**Comment by willbunnett** [comment]
Hmm, that does seem to be an oversight. How would you propose to add them?

**Comment by jakewelchert** [comment]
@willbunnett I can attempt to put them in the footer somehow, similar to the launch page.

**Comment by willbunnett** [comment]
How much time do you estimate this will add?

**Comment by jakewelchert** [comment]
@willbunnett Not much at all, especially if we're thinking just in the footer. I'll add and have you review.

**Comment by jakewelchert** [comment]
Resolved.
